//Auto-generated by AnimationStateEnumGenerator at SpookyTools/Entity System/Generate Animation States Enum.
//DO NOT modify manually.
namespace SpookyCore.EntitySystem
{
    public enum EntityAnimState
    {
        None,
        Player_Idle,
        Player_Walk,
        Player_Run,
        Player_Jump,
    }
}
