//Auto-generated by AnimationStateEnumGenerator at SpookyTools/Entity System/Generate Animation States Enum.
//DO NOT modify manually.
namespace SpookyCore.Runtime.EntitySystem
{
    public enum EntityAnimState
    {
        None,
        BasicEnemy_Idle,
        BasicEnemy_Walk,
        BasicEnemy_Run,
        BasicEnemy_Jump,
        BasicEnemy_Attack,
        BasicEnemy_Damaged,
        BasicEnemy_Dead,
        Player_Idle,
        Player_Walk,
        Player_Run,
        Player_Jump,
        Player_Attack,
        Player_Damaged,
        Player_Dead,
    }
}
