//Auto-generated by EntityIDEditorWindow, configurable via SpookyTools/EntitySystem/EntityID Editor.
//DO NOT change manually.
using System;

namespace SpookyCore.Runtime.EntitySystem
{
    [Serializable]
    public enum EntityID
    {
        MISSING_ID = 0,

        ___________________________________PLAYER = 100,
        Player = 101,

        ___________________________________ENEMY = 200,
        Enemy = 201,

        ___________________________________PLATFORM = 300,
        Platform = 301,
    }

    public static class EntityType
    {
        public static bool IsPlayer(this EntityID entityID)
        {
            var intValue = (int)entityID;
            return intValue is > 100 and < 200;
        }

        public static bool IsEnemy(this EntityID entityID)
        {
            var intValue = (int)entityID;
            return intValue is > 200 and < 300;
        }

        public static bool IsPlatform(this EntityID entityID)
        {
            var intValue = (int)entityID;
            return intValue is > 300 and < 400;
        }

    }
}
